# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_goods_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='desc',
            field=models.TextField(default='', max_length=200, verbose_name='文本介绍'),
        ),
    ]
