# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='desc',
        ),
    ]
