# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_goods_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], max_length=30, verbose_name='当前类别'),
        ),
    ]
