# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopingcart',
            old_name='goods_nums',
            new_name='nums',
        ),
    ]
