# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180626_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='goods_nums',
            new_name='goods_num',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_sn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号'),
        ),
    ]
