# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180627_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_amount',
            new_name='order_mount',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_message',
            new_name='post_script',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signing_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signing_name',
            new_name='signer_name',
        ),
    ]
