# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '短信验证码'},
        ),
    ]
