# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='signing_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='signing_name',
            new_name='signer_name',
        ),
    ]
